############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1
pre = "<i class='fas fa-home'></i>"

[[main]]
name = "About"
url = "about/"
weight = 2
pre = "<i class='fas fa-info-circle'></i>"
hasChildren = true

  [[main]]
  parent = "About"
  name = "What's WFST"
  url = "about/about/"
  weight = 1

  [[main]]
  parent = "About"
  name = "Telescope"
  url = "about/telescope/"
  weight = 2

  [[main]]
  parent = "About"
  name = "Site"
  url = "location/"
  weight = 3

  [[main]]
  parent = "About"
  name = "Camera"
  url = "about/camera/"
  weight = 4

  [[main]]
  parent = "About"
  name = "Team"
  url = "about/team/"
  weight = 5

[[main]]
name = "Science"
url = "science/"
weight = 3
pre = "<i class='fas fa-atom'></i>"
hasChildren = true

  [[main]]
  parent = "Science"
  name = "Time-domain Science"
  weight = 1
  url = "science/time-domain/"
      
  
  [[main]]
  parent = "Science"
  name = "Asteroids and the Solar System"
  weight = 2
  url = "science/asteroids-and-the-solar-system/"
      
  [[main]]
  parent = "Science"
  name = "Milky Way and its Satellites"
  weight = 3
  url = "science/milky-way-and-its-satellites/"

  [[main]]
  parent = "Science"
  name = "Galaxy formation and cosmology"
  weight = 4
  url = "science/galaxy-formation-and-cosmology/"

[[main]]
name = "Survey & Data"
url = "survey-and-data/"
weight = 4
pre = "<i class='fas fa-database'></i>"
hasChildren = true

  [[main]]
  parent = "Survey & Data"
  name = "Survey Strategy"
  weight = 1
  url = "survey-and-data/survey-strategy"

  [[main]]
  parent = "Survey & Data"
  name = "Data reduction and management"
  weight = 2
  url = "survey-and-data/data-reduction-and-management/"

  [[main]]
  parent = "Survey & Data"
  name = "Alert stream"
  weight = 3
  url = "survey-and-data/alert-stream/"

  [[main]]
  parent = "Survey & Data"
  name = "Data release"
  weight = 4
  url = "survey-and-data/data-release/"


[[main]]
weight = 5
name = "Publications"
pre = "<i class='fas fa-book'></i>"
hasChildren = true

  [[main]]
  parent = "Publications"
  name = "Publication"
  url = "publications/publication/"
  weight = 1

  [[main]]
  parent = "Publications"
  name = "Research highlights"
  url = "publications/highlights/"
  weight = 2

[[main]]
weight = 6
name = "news-and-meetings"
pre = "<i class='fas fa-clock'></i>"
hasChildren = true

  [[main]]
  parent = "news-and-meetings"
  name = "News"
  url = "news-and-meetings/news/"
  weight = 1

  [[main]]
  parent = "news-and-meetings"
  name = "meetings"
  url = "news-and-meetings/meetings/"
  weight = 2

[[main]]
weight = 7
name = "education-and-outreach"
pre = "<i class='fas fa-graduation-cap'></i>"
hasChildren = true

  [[main]]
  parent = "education-and-outreach"
  name = "education"
  url = "education-and-outreach/education/"
  weight = 1

  [[main]]
  parent = "education-and-outreach"
  name = "multimedia"
  url = "education-and-outreach/multimedia/"
  weight = 2

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Science"
url = "science/"
weight = 3

[[footer]]
name = "Survey & Data"
url = "survey-and-data/"
weight = 4

[[footer]]
name = "Publications"
url = "publications/"
weight = 5

[[footer]]
name = "News"
url = "news/news"
weight = 6

[[footer]]
name = "education-and-outreach"
url = "join-us/join-us"
weight = 7